### ISSUE TITLE
Where to add bcrypt method stub?

### ISSUE THREAD

**Issue by bjfish** [jruby/jruby-truffle-gem-test-pack#4]
I'd like to add this stubbed method to stub-bcrypt.rb
```
module BCrypt
  class Engine
    def self.__bc_salt
    end
  end
end
```
Could you point me where to add this stubbed method?

I'm working on fixing this broken build https://travis-ci.org/graalvm/truffleruby/jobs/193597157
for this PR: https://github.com/graalvm/truffleruby/pull/10

**Comment by chrisseaton** [comment]
@pitr-ch do you know where workarounds like this should go?

Why do we need this though? Is BCrypt something in the stdlib? Can you give me the context?

**Comment by bjfish** [comment]
@chrisseaton I'm trying to update the RUBY_PLATFORM in the PR mentioned in the description. The ecosystem tests fail because activemodel uses the BCrypt gem and this class branches on platform to try to remove this method which doesn't exist '__bc_salt'. I don't think the removal of the method will cause any issues because it appears we stub the whole gen_salt method where it would have been used. 

I search around the projects a little looking for this stub but couldn't find it yet. I thought it was in a yml file possibly. I should be able to find it later today once I have more time to search. I'll close this issue if I'm able to find it.

**Comment by bjfish** [comment]
I think I've found where it goes now. 
https://github.com/graalvm/truffleruby/blob/truffle-head/lib/ruby/truffle/jruby-truffle-tool/lib/config.rb

**Comment by pitr-ch** [comment]
@bjfish yeah config is the right place.
